post:
  tags:
    - Application Owner Campaigns
  summary: Lock Campaign
  description: >-
    This API is used to lock campaign after validating whether Application Owner
    campaign is completed or not.

    The `Authorization` must have `Bearer` followed by `Token`.

    Mandatory params:

    `campaignId`

    `verifier`

    Optional params:

    `certkey`
  operationId: lockCampaign2
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            campaignId:
              type: string
              example: '305'
            verifier:
              type: string
              example: admin
        examples:
          Lock Campaign:
            value:
              campaignId: '305'
              verifier: admin
  responses:
    '200':
      description: Lock Campaign - SUCCESS
      headers:
        Access-Control-Allow-Credentials:
          schema:
            type: string
            example: 'true'
        Access-Control-Allow-Origin:
          schema:
            type: string
            example: 'http://localhost'
        Cache-Control:
          schema:
            type: string
            example: 'post-check=0, pre-check=0'
        Date:
          schema:
            type: string
            example: 'Wed, 17 Jun 2020 02:01:16 GMT'
        Expires:
          schema:
            type: string
            example: 'Sun, 7 May 1995 12:00:00 GMT'
        Referrer-Policy:
          schema:
            type: string
            example: same-origin
        Set-Cookie:
          schema:
            type: string
            example: CCSRF-TOKEN=e625d595-9cbd-4097-8ed5-4296282340c4; Path=/
        Strict-Transport-Security:
          schema:
            type: string
            example: max-age=7776000; includeSubdomains
        X-Content-Type-Options:
          schema:
            type: string
            example: nosniff
        X-Frame-Options:
          schema:
            type: string
            example: DENY
      content:
        application/json:
          schema:
            type: object
            properties:
              Total Incomplete certification:
                type: array
                items: {}
                example: []
              Total locked certification:
                type: array
                items:
                  type: string
                  example: AOTest0610__1 - AN2022 (ANtest UserAN2022)
                example:
                  - AOTest0610__1 - AN2022 (ANtest UserAN2022)
              errorCode:
                type: string
                example: '0'
              lockedcertkey:
                type: array
                items:
                  type: number
                  example: 12877
                example:
                  - 12877
              msg:
                type: string
                example: Success
          examples:
            Lock Campaign - SUCCESS:
              value:
                Total Incomplete certification: []
                Total locked certification:
                  - AOTest0610__1 - AN2022 (ANtest UserAN2022)
                errorCode: '0'
                lockedcertkey:
                  - 12877
                msg: Success
