# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
docs/saviynt-eic-api-5.0.yaml:
  operation-4xx-response:
    - '#/paths/~1api~1login/post/responses'
    - '#/paths/~1oauth~1access_token/post/responses'
    - '#/paths/~1createUser/post/responses'
    - '#/paths/~1updateUser/post/responses'
    - '#/paths/~1uploadUserRequest/post/responses'
    - '#/paths/~1getUser/post/responses'
    - '#/paths/~1user/get/responses'
    - '#/paths/~1addremoveuserfromrole/post/responses'
    - '#/paths/~1getAccessDetailsForUser/post/responses'
    - '#/paths/~1getEntDetailsforUsers/get/responses'
    - '#/paths/~1getRoleDetailsforUsers/get/responses'
    - '#/paths/~1authenticateUser/post/responses'
    - '#/paths/~1validateUserData/post/responses'
    - '#/paths/~1getSavRoles/get/responses'
    - '#/paths/~1getAccounts/post/responses'
    - '#/paths/~1exportAccount/post/responses'
    - '#/paths/~1createAccount/post/responses'
    - '#/paths/~1updateAccount/post/responses'
    - '#/paths/~1assignAccountToUser/post/responses'
    - '#/paths/~1assignAccountToEntitlement/post/responses'
    - '#/paths/~1removeAccountToEntitlement/post/responses'
    - '#/paths/~1createPrivilege/put/responses'
    - '#/paths/~1updatePrivilege/put/responses'
    - '#/paths/~1deletePrivilege/put/responses'
    - '#/paths/~1getEntitlements/post/responses'
    - '#/paths/~1getChildEntitlements/get/responses'
    - '#/paths/~1createUpdateEntitlement/post/responses'
    - '#/paths/~1getEntitlementValuesForEndpoint/post/responses'
    - '#/paths/~1getListofPrivileges/post/responses'
    - '#/paths/~1removeEntitlementsFromRole/post/responses'
    - '#/paths/~1addrole/post/responses'
    - '#/paths/~1getRoles/post/responses'
    - '#/paths/~1getFireFighterRoles/post/responses'
    - '#/paths/~1removerole/post/responses'
    - '#/paths/~1createEndpoint/post/responses'
    - '#/paths/~1updateEndpoint/put/responses'
    - '#/paths/~1getEndpoints/post/responses'
    - '#/paths/~1createEntitlementType/post/responses'
    - '#/paths/~1updateEntitlementType/put/responses'
    - '#/paths/~1getEntitlementTypes/get/responses'
    - '#/paths/~1createDynamicAttribute/post/responses'
    - '#/paths/~1updateDynamicAttribute/put/responses'
    - '#/paths/~1fetchDynamicAttribute/get/responses'
    - '#/paths/~1deleteDynamicAttribute/delete/responses'
    - '#/paths/~1deleteEntitlementType/delete/responses'
    - '#/paths/~1createSecuritySystem/post/responses'
    - '#/paths/~1updateSecuritySystem/put/responses'
    - '#/paths/~1getSecuritySystems/get/responses'
    - '#/paths/~1deleteSecuritySystem/delete/responses'
    - '#/paths/~1createUpdateUserGroup/post/responses'
    - '#/paths/~1addRemoveUserFromUserGroup/post/responses'
    - '#/paths/~1deleteUserGroup/post/responses'
    - '#/paths/~1createOrganization/post/responses'
    - '#/paths/~1updateOrganization/put/responses'
    - '#/paths/~1getOrganization/get/responses'
    - '#/paths/~1deleteOrganization/post/responses'
    - '#/paths/~1getConnections/post/responses'
    - '#/paths/~1getConnectionDetails/post/responses'
    - '#/paths/~1deleteConnection/delete/responses'
    - '#/paths/~1createDataset/post/responses'
    - '#/paths/~1getDatasetValues/get/responses'
    - '#/paths/~1updateDatasetValues/post/responses'
    - '#/paths/~1deleteDataset/post/responses'
    - '#/paths/~1uploadDatasetCSV/post/responses'
    - '#/paths/~1updateDataset/post/responses'
    - '#/paths/~1fetchControlList/post/responses'
    - '#/paths/~1fetchControlDetails/post/responses'
    - '#/paths/~1runAnalyticsControls/post/responses'
    - '#/paths/~1fetchRuntimeControlsData/post/responses'
    - '#/paths/~1fetchRuntimeControlsDataV2/post/responses'
    - '#/paths/~1fetchControlListES/get/responses'
    - '#/paths/~1fetchControlAttributes/post/responses'
    - '#/paths/~1fetchControlDetailsES/post/responses'
    - '#/paths/~1updateUserRequest/put/responses'
    - '#/paths/~1getrequestableusers/get/responses'
    - '#/paths/~1createEnterpriseRoleRequest/post/responses'
    - '#/paths/~1updateEnterpriseRoleRequest/post/responses'
    - '#/paths/~1getUserRequestableEntitlements/post/responses'
    - '#/paths/~1validateEntitlementRequestData/post/responses'
    - '#/paths/~1createrequest/post/responses'
    - '#/paths/~1createOrganizationRequest/post/responses'
    - '#/paths/~1updateOrganizationRequest/put/responses'
    - '#/paths/~1createautoapprovedrequest/post/responses'
    - '#/paths/~1createbirthrightrequest/post/responses'
    - '#/paths/~1updateRequest/post/responses'
    - '#/paths/~1fetchRequestHistory/post/responses'
    - '#/paths/~1fetchRequestHistoryDetails/post/responses'
    - '#/paths/~1cancelPendingRequest/post/responses'
    - '#/paths/~1getPendingRequests/post/responses'
    - '#/paths/~1fetchRequestApprovalDetails/post/responses'
    - '#/paths/~1ApproveRejectDetailRequest/post/responses'
    - '#/paths/~1getPendingApprovals/post/responses'
    - '#/paths/~1approveRejectRequest/post/responses'
    - '#/paths/~1createtask/post/responses'
    - '#/paths/~1completetask/post/responses'
    - '#/paths/~1updateTasks/post/responses'
    - '#/paths/~1discontinueTask/post/responses'
    - '#/paths/~1discontinueAllPendingTask/post/responses'
    - '#/paths/~1fetchTasks/post/responses'
    - '#/paths/~1fetchRequestAccessAttributes/post/responses'
    - '#/paths/~1checkTaskStatus/post/responses'
    - '#/paths/~1getDelegateUserList/get/responses'
    - '#/paths/~1createDelegate/post/responses'
    - '#/paths/~1fetchDelegatesList/post/responses'
    - '#/paths/~1editDelegate/post/responses'
    - '#/paths/~1deleteDelegate/post/responses'
    - '#/paths/~1fetchAttestationsList/post/responses'
    - '#/paths/~1fetchAttestationDetails/post/responses'
    - '#/paths/~1certifyUserManagerRequests/post/responses'
    - '#/paths/~1fetchAttAccEntDetails/post/responses'
    - '#/paths/~1approveRejectAttAccEntDetails/post/responses'
    - '#/paths/~1lockAttestation/post/responses'
    - '#/paths/~1fetchCampaignList/post/responses'
    - '#/paths/~1fetchCampaignDetails/post/responses'
    - '#/paths/~1certifyUserManagerforCampaign/post/responses'
    - '#/paths/~1fetchCampaignAccEntDetails/post/responses'
    - '#/paths/~1approverejectCampaignAccEntDetails/post/responses'
    - '#/paths/~1lockCampaign/post/responses'
    - '#/paths/~1reassignUserManagerforCampaign/post/responses'
    - '#/paths/~1consultUserManagerforCampaign/post/responses'
    - '#/paths/~1consultCampaignAccEntDetails/post/responses'
    - '#/paths/~1reAssignUserManagerStep2AccEntDetails/post/responses'
    - '#/paths/~1consultEOforCampaign/post/responses'
    - '#/paths/~1consultEOCampaignAccEntDetails/post/responses'
    - '#/paths/~1fetchEntOwnerCampaignAccEntDetails/post/responses'
    - '#/paths/~1getFlatResponseEntOwnerCampaignAccEntDetails/post/responses'
    - '#/paths/~1approverejectEntOwnerCampaignAccEntDetails/post/responses'
    - '#/paths/~1certifyEntOwnerforCampaign/post/responses'
    - '#/paths/~1reassignEntOwnerCampaignAccEnt/post/responses'
    - '#/paths/~1reassignEntOwnerCampaignAccEntDetailsStep2/post/responses'
    - '#/paths/~1fetchAppOwnerCampaignAccEntDetails/post/responses'
    - '#/paths/~1approverejectAppOwnerCampaignAccEntDetails/post/responses'
    - '#/paths/~1lockApplicationOwnerCampaign/post/responses'
    - '#/paths/~1consultAppOwnerCampaignAccEntDetails/post/responses'
    - '#/paths/~1reAssignAppOwnerCampaignAccEntDetails/post/responses'
    - '#/paths/~1fetchCertificationList/post/responses'
    - '#/paths/~1discontinueCampaign/post/responses'
    - '#/paths/~1reAssignCertification/post/responses'
    - '#/paths/~1sapSODEvaluation/post/responses'
    - '#/paths/~1sodEvaluation/post/responses'
    - '#/paths/~1addMCRiskAccount/post/responses'
    - '#/paths/~1uploadSODRuleset/post/responses'
    - '#/paths/~1getSavSecurityQuestions/post/responses'
    - '#/paths/~1fetchSavUserQuestions/post/responses'
    - '#/paths/~1validateSecurityAnswers/post/responses'
    - '#/paths/~1createSavSecurityQuestions/post/responses'
    - '#/paths/~1createSavPasswordPolicy/post/responses'
    - '#/paths/~1changePassword/post/responses'
    - '#/paths/~1createUpdateTrigger/post/responses'
    - '#/paths/~1checkJobStatus/post/responses'
    - '#/paths/~1deleteTrigger/post/responses'
    - '#/paths/~1runJobTrigger/post/responses'
    - '#/paths/~1fetchJobMetadata/post/responses'
    - '#/paths/~1createTriggers/post/responses'
    - '#/paths/~1resumePauseJobs/post/responses'
    - '#/paths/~1uploadSchemaFile/post/responses'
    - '#/paths/~1ECM~1testConnection/post/responses'
    - '#/paths/~1importData/post/responses'
    - '#/paths/~1checkImportStatus/post/responses'
    - '#/paths/~1forceComplete/post/responses'
    - '#/paths/~1sendEmail/post/responses'
    - '#/paths/~1mobileDashboard/post/responses'
    - '#/paths/~1retrieveDashboardAccountData/post/responses'
    - '#/paths/~1retrieveDashboardData/post/responses'
    - '#/paths/~1getAccessRecommendations/post/responses'
    - '#/paths/~1exportTransportPackage/post/responses'
    - '#/paths/~1importTransportPackage/post/responses'
    - '#/paths/~1transportPackageStatus/get/responses'
    - '#/paths/~1rules~1technical/get/responses'
    - '#/paths/~1rules~1technical/put/responses'
    - '#/paths/~1rules~1technical/post/responses'
    - '#/paths/~1rules~1technical/delete/responses'
