# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: api-specs/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
apis:
  saviynt-rest@5.0:
  root: api-specs/openapi.yaml
  labels:
      - production