openapi: 3.0.3
info:
  title: Swagger SOD - OpenAPI 3.0
  description: |-
  
    SOD APIs are based on the OpenAPI 3.0 specification. 
    
    You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). 
    
    In the this iteration of the SOD APIs, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OpenAPI Specification (OAS) 3.0.
    
    The SOD API will offer a comprehensive suite of endpoints to manage various aspects of Segregation of Duties, including: Violations management, Business functions and risk definitions, Function objects and entitlements, Mitigating controls and simulations, Job scheduling and execution, Ruleset creation and maintenance

    
    Some useful links:
    - [The SOD API repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the SOD](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
    
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://client.saviyntcloud.com/api/v3
  
  
tags:
  - name: risk
    description: Everything about SOD Risks
  - name: function
    description: Everything about SOD Functions
paths:
  /risk:
    put:
      tags:
        - risk
      summary: Update an existing risk
      description: Update an existing risk by Id
      operationId: updateRisk
      security:
        - sod_auth:
            - write:risks
            - read:risks
    post:
      tags:
        - risk
      summary: Add a new risk
      description: Add a new risk
      operationId: addRisk
      security:
        - sod_auth:
            - write:risks
            - read:risks
  /risk/findByStatus:
    get:
      tags:
        - risk
      summary: Finds risks by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findRisksByStatus
      security:
        - sod_auth:
            - write:risks
            - read:risks
  /risk/findByPriority:
    get:
      tags:
        - risk
      summary: Finds Risks by Priority
      description: Multiple Priority can be provided with comma separated strings. Use High, Low, Critical for testing.
      operationId: findRisksByPriority
      security:
        - sod_auth:
            - write:risks
            - read:risks
  /risk/{riskId}:
    get:
      tags:
        - risk
      summary: Find risk by ID
      description: Returns a single risk
      operationId: getRiskById
      security:
        - api_key: []
        - sod_auth:
            - write:risks
            - read:risks
    post:
      tags:
        - risk
      summary: Updates a risk with form data
      description: ''
      operationId: updateRiskWithForm
      security:
        - sod_auth:
            - write:risks
            - read:risks
    delete:
      tags:
        - risk
      summary: Deletes a risk
      description: delete a risk
      operationId: deleteRisk
      security:
        - sod_auth:
            - write:risks
            - read:risks
  /function:
    put:
      tags:
        - function
      summary: Update an existing function
      description: Update an existing function by Id
      operationId: updateFunction
      security:
        - sod_auth:
            - write:functions
            - read:functions
    post:
      tags:
        - function
      summary: Add a new function
      description: Add a new function
      operationId: addFunction
      security:
        - sod_auth:
            - write:functions
            - read:functions
  /function/findByStatus:
    get:
      tags:
        - function
      summary: Finds functions by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findFunctionsByStatus
      security:
        - sod_auth:
            - write:functions
            - read:functions
  /function/findByPriority:
    get:
      tags:
        - function
      summary: Finds functions by Priority
      description: Multiple Priority can be provided with comma separated strings. Use High, Low, Critical for testing.
      operationId: findFunctionsByPriority
      security:
        - sod_auth:
            - write:functions
            - read:functions
  /function/{functionId}:
    get:
      tags:
        - function
      summary: Find function by ID
      description: Returns a single function
      operationId: getFunctionById
      security:
        - api_key: []
        - sod_auth:
            - write:functions
            - read:functions
    post:
      tags:
        - function
      summary: Updates a function with form data
      description: ''
      operationId: updateFunctionWithForm
      security:
        - sod_auth:
            - write:functions
            - read:functions
    delete:
      tags:
        - function
      summary: Deletes a function
      description: delete a function
      operationId: deleteFunction
      security:
        - sod_auth:
            - write:functions
            - read:functions
components:
  securitySchemes:
    sod_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://sod.swagger.io/oauth/authorize
          scopes:
            write:risks: modify risks
            read:risks: read risks
            write:functions: modify functions
            read:functions: read functions
    api_key:
      type: apiKey
      name: api_key
      in: header