post:
  tags:
    - roles
  summary: Add Role
  description: |-
    This API adds role to user.
    The `Authorization` must have `Bearer` followed by `Token`.
    Mandatory params:
    `username`,
    `rolename`
  operationId: addRole
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            rolename:
              type: string
              example: Fire Fighter
            username:
              type: string
              example: johndoe
        examples:
          Add Role:
            value:
              rolename: Fire Fighter
              username: johndoe
  responses:
    '200':
      description: Add Role
      headers:
        Date:
          schema:
            type: string
            example: Wed, 24 Oct 2018 21:17:09 GMT
        Server:
          schema:
            type: string
            example: Apache-Coyote/1.1
        Set-Cookie:
          schema:
            type: string
            example: CCSRF-TOKEN=9aabdb9e-22bc-4d27-9ed5-22661edc2a38; Path=/
        X-Content-Type-Options:
          schema:
            type: string
            example: nosniff
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: ' Tasks created. IDs:: 673975 '
          examples:
            Add Role:
              value:
                message: ' Tasks created. IDs:: 673975 '
