openapi: 3.0.0
info:
  title: Saviynt
  version: 1.0.0
  description: Fetch analytics data, Fetch request history, Disable an account, Get user details from Saviynt, Assign user to account
servers:
  - url: '{InstanceURL}'
paths:
  '/ECM/api/v5/fetchRuntimeControlsDataV2':
    post:
      operationId: fetchanalyticsdata
      summary: Fetch Analytics Data
      description: Fetch Analytics Data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                analyticsname:
                  type: string
                  description: The analytic to get data from
                  example: "Actual SoD"
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/fetchAnalyticDataResponse"
      security:
        - bearerAuth: []
      x-ms-api-interaction: unrestricted

  '/ECM/api/v5/fetchRequestHistory':
    post:
      operationId: fetchRequestHistory
      summary: Fetch the Request History based on the criteria provided
      description: Fetch the Request History based on the criteria provided
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Username in Saviynt
                  example: "admin"
                status:
                  type: array
                  description: Request status (OPEN/DRAFT/INPROCESS/COMPLETED/EXPIRED/DISCONTINUED)
                  example: ["OPEN", "EXPIRED"]
                  items:
                    type: string
                    enum: ["OPEN", "DRAFT", "INPROCESS", "COMPLETED", "EXPIRED", "DISCONTINUED"]
                  nullable: true
                requestkey:
                  type: string
                  description: Request key
                  nullable: true
                requestedfor:
                  type: string
                  description: Requested for name
                  nullable: true
                requestedby:
                  type: string
                  description: Requested by name
                  nullable: true
                sort:
                  type: string
                  description: Sort by (requestsubmittedon/duedate/requestid)
                  nullable: true
                order:
                  type: string
                  description: Sort order (asc or desc)
                  nullable: true
                requestid:
                  type: string
                  description: Request ID
                  nullable: true
                duedatestart:
                  type: string
                  description: Due date start (MM/dd/yyyy)
                  nullable: true
                duedateend:
                  type: string
                  description: Due date end (MM/dd/yyyy)
                  nullable: true
                submitdatestart:
                  type: string
                  description: Submit date start (MM/dd/yyyy)
                  nullable: true
                submitdateend:
                  type: string
                  description: Submit date end (MM/dd/yyyy)
                  nullable: true
                endpoint:
                  type: string
                  description: Endpoint
                  nullable: true
                securitysystem:
                  type: string
                  description: Security system
                  nullable: true
                firstname:
                  type: string
                  description: First name of requestedfor user
                  nullable: true
                lastname:
                  type: string
                  description: Last name of requestedfor user
                  nullable: true
                assignee:
                  type: array
                  description: List of usernames for assignee
                  items:
                    type: string
                  nullable: true
                requesttype:
                  type: array
                  description: List of request types (ADD, UPDATEACCOUNT, NEWACCOUNT, DEL, NEWROLEREQUEST, CREATEROLE, MODIFYROLE, CREATEUSER, UPDATEUSER, EXTENDACCESS, etc.)
                  items:
                    type: string
                  nullable: true
                approvedby:
                  type: array
                  description: List of usernames for approvedby
                  items:
                    type: string
                  nullable: true
                rejectedby:
                  type: array
                  description: List of usernames for rejectedby
                  items:
                    type: string
                  nullable: true
                max:
                  type: integer
                  description: Maximum number of records to return
                  nullable: true
                offset:
                  type: integer
                  description: Offset for pagination
                  nullable: true
                showentitlementdetails:
                  type: boolean
                  description: Show entitlement details (true/false)
                  nullable: true
                entresponsefields:
                  type: array
                  description: Entitlement response fields
                  items:
                    type: string
                  nullable: true
                exactmatch:
                  type: boolean
                  description: Exact match (true/false)
                  nullable: true
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/fetchRequestHistoryResponse"
      security:
        - bearerAuth: []
      x-ms-api-interaction: unrestricted

  '/ECM/api/v5/user':
    get:
      operationId: getUser
      summary: Retrieve user details based on query parameters
      description: Retrieve user details based on the provided query parameters such as firstname, lastname, username, jobcode, accountExpired, statuskey, departmentname, etc. Multiple values for a single search criteria can be passed as comma separated values (e.g., Username:john,frank,sam)
      parameters:
        - name: q
          in: query
          description: Query parameter to specify the search criteria (e.g., Firstname:John, Lastname:Doe, etc.). Pass in multiple values to a single search criteria using comma separated values (e.g., Username:john,frank,sam)
          required: true
          schema:
            type: string
            example: "lastname:Doe,Smith,Patrick,Murphy"
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getUserDetails"
      security:
        - bearerAuth: []
      x-ms-api-interaction: unrestricted

  '/ECM/api/v5/assignAccountToUser':
    post:
      operationId: assignAccountToUser
      summary: Assign an account to a user
      description: Assign an account to a user in Saviynt with the parameters provided such as account name, username, security system and endpoint. If only one of security system or endpoint are provided, then pass the same value to both security system and endpoint.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                securitysystem:
                  type: string
                  description: Name of the Security System or Application in Saviynt.
                endpoint:
                  type: string
                  description: Name of the Endpoint corresponding to the Security System.
                accountname:
                  type: string
                  description: Account name to be assigned.
                username:
                  type: string
                  description: Username of the user to whom the account has to be assigned.
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    description: Error code (if any)
                  message:
                    type: string
                    description: Result message
      security:
        - bearerAuth: []
      x-ms-api-interaction: unrestricted
  /ECM/api/v5/createrequest:
    post:
      summary: Create Request to Disable Account in Saviynt
      description: |
        Disable account in Saviynt when the account name and endpoint are provided. The requesttype is always set to DISABLEACCOUNT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - requesttype
                - accountname
                - endpoint
              properties:
                requesttype:
                  type: string
                  description: The type of request (e.g., DISABLEACCOUNT).
                  enum:
                    - DISABLEACCOUNT
                accountname:
                  type: string
                  description: The name of the account to be disabled.
                endpoint:
                  type: string
                  description: The endpoint or the application in which the account is to be disabled
                businessjustification:
                  type: string
                  description: Justification for the request.If no justification is provided, always default to "No account owner identified. Disabled from Copilot for Security".
                  example: No account owner identified. Account disabled from Microsoft Copilot for Security.
      responses:
        '200':
          description: Request created successfully.
        '400':
          description: Invalid request body.
        '401':
          description: Unauthorized - Missing or invalid authentication token.
        '403':
          description: Forbidden - The user does not have permission to perform this action.
        '500':
          description: Internal server error - Something went wrong on the server side.
      security:
        - bearerAuth: []
      x-ms-api-interaction: unrestricted
components:
  schemas:
    fetchAnalyticDataResponse:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              RULESET:
                type: string
                description: Ruleset name
              ACTUALRISK:
                type: string
                description: Actual risk
              RISKCODE:
                type: string
                description: Risk code
              DESCRIPTION:
                type: string
                description: Description
              USERNAME:
                type: string
                description: Username
              ACCOUNTNAME:
                type: string
                description: Account name

    fetchRequestHistoryResponse:
      type: object
      properties:
        msg:
          type: string
          description: Message indicating the result of the request
        totalcount:
          type: integer
          description: Total count of requests
        count:
          type: integer
          description: Count of requests in the response
        errorCode:
          type: string
          description: Error code (if any)
        requests:
          type: array
          items:
            type: object
            properties:
              requestid:
                type: string
                description: Request ID
              reqkey:
                type: string
                description: Request key
              requesttype:
                type: string
                description: Request type
              requestor:
                type: string
                description: Requestor name
              requestedfor:
                type: string
                description: Requested for name
              requestsubmittedon:
                type: string
                description: Request submitted on
              duedate:
                type: string
                description: Due date
              status:
                type: string
                description: Request status
              assignee:
                type: string
                description: Assignee name
              endpoints:
                type: string
                description: Endpoints
              endpointname:
                type: string
                description: Endpoint name
              requestandtaskstatus:
                type: string
                description: Request and task status

    getUserDetails:
      type: object
      properties:
        msg:
          type: string
          description: Message indicating the result of the request
        count:
          type: integer
          description: Count of users in the response
        errorCode:
          type: string
          description: Error code (if any)
        results:
          type: array
          items:
            type: object
            properties:
              accountLocked:
                type: string
                description: Account locked status of the user
              owner:
                type: string
                description: Owner of the user
              localAuthEnabled:
                type: string
                description: Local authentication enabled status of the user
              firstname:
                type: string
                description: First name of the user
              manager:
                type: string
                description: Manager of the user
              preferedFirstName:
                type: string
                description: Preferred first name of the user
              createdate:
                type: string
                description: Create date of the user
              startdate:
                type: string
                description: Start date of the user
              userKey:
                type: integer
                description: User key of the user
              failedTries:
                type: string
                description: Number of failed login attempts
              enabled:
                type: string
                description: Enabled status of the user
              lastname:
                type: string
                description: Last name of the user
              updatedate:
                type: string
                description: Update date of the user
              systemUserName:
                type: string
                description: System username of the user
              createdBy:
                type: string
                description: User who created the user
              statuskey:
                type: string
                description: Status key of the user
              accountExpired:
                type: string
                description: Account expired status of the user
              lastPasswordUpdateDate:
                type: string
                description: Last password update date of the user
              passwordExpired:
                type: string
                description: Password expired status of the user
              email:
                type: string
                description: Email of the user
              updateuser:
                type: string
                description: User who last updated the user
              username:
                type: string
                description: Username of the user
        order:
          type: string
          description: Order of the response (ASC/DESC)

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer