openapi: 3.0.0
info:
  title: Saviynt
  version: 1.0.0
  description: Get access details for users, get user details, get organization details, get list of users with specified Sav role, get dependent entitlements
servers:
  - url: '{InstanceURL}'
paths:
  '/ECM/api/v5/getAccessDetailsForUser':
    get:
      summary: Get Access Details for Users
      description: Retrieve account and entitlement details for specified users and endpoint.
      operationId: getAccessDetailsforUsers
      parameters:
        - name: username
          in: query
          required: true
          description: The username for which entitlement details are being requested.
          schema:
            type: string
            example: "2706"
        - name: endpoint
          in: query
          required: false
          description: The endpoint for which entitlement details are being requested. If no endpoint details are provided, return all the access details
          schema:
            type: string
            example: "SAP"
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getAccountEntitlementResponse"
      security:
        - bearerAuth: []
      x-ms-api-interaction: unrestricted

  '/ECM/api/v5/user':
    get:
      operationId: getUser
      summary: Retrieve user details based on query parameters
      description: Retrieve user details based on the provided query parameters such as firstname, lastname, username, jobcode, accountExpired, statuskey, departmentname, etc. Multiple values for a single search criteria can be passed as comma separated values (e.g., Username:john,frank,sam). Customproperty1 refers to the user risk score.
      parameters:
        - name: q
          in: query
          description: Query parameter to specify the search criteria (e.g., Firstname:John, Lastname:Doe, etc.). Pass in multiple values to a single search criteria using comma separated values (e.g., Username:john,frank,sam)
          required: true
          schema:
            type: string
            example: "lastname:Doe,Smith,Patrick,Murphy"
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getUserDetails"
      security:
        - bearerAuth: []
      x-ms-api-interaction: unrestricted
  /ECM/api/v5/getOrganization:
    get:
      summary: Get Organization Details
      description: Fetches details of the organization based on the provided criteria.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                filterCriteria:
                  type: object
                  description: The criteria to filter by
                  properties:
                    organizationname:
                      type: string
                      description: Name of the organization to filter by
                      example: Acme
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOrganizationResponse"
      security:
        - bearerAuth: []
  /ECMv6/api/userms/savroles/{roleName}/users:
    get:
      summary: Get Users by Sav Role
      description: Retrieve a list of users with the specified Sav role
      parameters:
        - name: roleName
          in: path
          required: true
          description: The role name to filter users by.
          schema:
            type: string
            example: "ROLE_ADMIN"
        - name: limit
          in: query
          required: true
          description: Limit the number of results returned.
          schema:
            type: integer
            default: 1000
        - name: offset
          in: query
          required: true
          description: Offset for pagination of results.
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResponse'
      security:
        - bearerAuth: []
  /ECM/api/v5/getChildEntitlements:
    get:
      summary: Get dependent Entitlements
      description: Retrieve dependent entitlements for a specified entitlement and endpoint.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parententitlementvalue:
                  type: string
                  description: The entitlement value to get dependent entitlements for.
                  example: "CN=Saviynt_Azure_Admin,CN=Builtin,DC=corpAD,DC=saviynt,DC=com"
                endpointname:
                  type: string
                  description: The endpoint name associated with the entitlements.
                  example: "ActiveDirectory"
              required:
                - parententitlementvalue
                - endpointname
      responses:
        '200':
          description: Successful response with dependent entitlements.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetChildEntitlementsResponse'
      security:
        - bearerAuth: []        
components:
  schemas:
    getAccountEntitlementResponse:
      type: object
      properties:
        msg:
          type: string
          description: Response message
          example: Successful
        displayCount:
          type: integer
          description: Number of access details displayed
          example: 1
        accessDetails:
          type: array
          items:
            type: object
            properties:
              userstatus:
                type: integer
                description: Status of the user
                example: 1
              entitlement_valuekey:
                type: integer
                description: Key of the entitlement value
                example: 194098
              entdisplayname:
                type: string
                description: Display name of the entitlement
                nullable: true
                example: null
              accountdisplayname:
                type: string
                description: Display name of the account
                example: "245947"
              endpointDisplayname:
                type: string
                description: Display name of the endpoint
                example: AWS
              endpointkey:
                type: integer
                description: Key of the endpoint
                example: 1
              systemname:
                type: string
                description: Name of the system
                example: AWS
              accountkey:
                type: integer
                description: Key of the account
                example: 3684
              entitlementType:
                type: string
                description: Type of the entitlement
                example: AWSPolicy
              entitlementTypeRequestForm:
                type: string
                description: Request form table for the entitlement type
                example: Request Form Table
              userkey:
                type: integer
                description: Key of the user
                example: 2511
              entdescription:
                type: string
                description: Description of the entitlement
                nullable: true
                example: null
              entitlementTypekey:
                type: integer
                description: Key of the entitlement type
                example: 59
              entitlementTypeDisplayname:
                type: string
                description: Display name of the entitlement type
                example: AWSPolicy
              accountname:
                type: string
                description: Name of the account
                example: "245947"
              accountstatus:
                type: string
                description: Status of the account
                example: Manually Suspended
              endpointname:
                type: string
                description: Name of the endpoint
                example: AWS
              entitlement_value:
                type: string
                description: Value of the entitlement
                example: "arn:aws:iam::661222050851:policy/CrossPolicy2"
              entstatus:
                type: integer
                description: Status of the entitlement
                example: 1
              securitysystemkey:
                type: integer
                description: Key of the security system
                example: 1
              securitysystemdisplayname:
                type: string
                description: Display name of the security system
                example: AWS
              username:
                type: string
                description: Username associated with the account
                example: "245947"
        errorCode:
          type: string
          description: Error code of the response
          example: "0"
        totalCount:
          type: integer
          description: Total count of access details
          example: 1
    getUserDetails:
      type: object
      properties:
        msg:
          type: string
          description: Message indicating the result of the request
        count:
          type: integer
          description: Count of users in the response
        errorCode:
          type: string
          description: Error code (if any)
        results:
          type: array
          items:
            type: object
            properties:
              accountLocked:
                type: string
                description: Account locked status of the user
              owner:
                type: string
                description: Owner of the user
              localAuthEnabled:
                type: string
                description: Local authentication enabled status of the user
              firstname:
                type: string
                description: First name of the user
              manager:
                type: string
                description: Manager of the user
              preferedFirstName:
                type: string
                description: Preferred first name of the user
              createdate:
                type: string
                description: Create date of the user
              startdate:
                type: string
                description: Start date of the user
              userKey:
                type: integer
                description: User key of the user
              failedTries:
                type: string
                description: Number of failed login attempts
              enabled:
                type: string
                description: Enabled status of the user
              lastname:
                type: string
                description: Last name of the user
              updatedate:
                type: string
                description: Update date of the user
              systemUserName:
                type: string
                description: System username of the user
              createdBy:
                type: string
                description: User who created the user
              statuskey:
                type: string
                description: Status key of the user
              accountExpired:
                type: string
                description: Account expired status of the user
              lastPasswordUpdateDate:
                type: string
                description: Last password update date of the user
              passwordExpired:
                type: string
                description: Password expired status of the user
              email:
                type: string
                description: Email of the user
              updateuser:
                type: string
                description: User who last updated the user
              username:
                type: string
                description: Username of the user
        order:
          type: string
          description: Order of the response (ASC/DESC)
    GetOrganizationResponse:
      type: object
      properties:
        msg:
          type: string
          example: "Successful"
        displayCount:
          type: integer
          example: 1
        accessDetails:
          type: array
          items:
            type: object
            properties:
              userstatus:
                type: integer
                example: 1
              entitlement_valuekey:
                type: integer
                example: 194098
              entdisplayname:
                type: string
                nullable: true
                example: null
              accountdisplayname:
                type: string
                example: "245947"
              endpointDisplayname:
                type: string
                example: "AWS"
              endpointkey:
                type: integer
                example: 1
              systemname:
                type: string
                example: "AWS"
              accountkey:
                type: integer
                example: 3684
              entitlementType:
                type: string
                example: "AWSPolicy"
              entitlementTypeRequestForm:
                type: string
                example: "Request Form Table"
              userkey:
                type: integer
                example: 2511
              entdescription:
                type: string
                nullable: true
                example: null
              entitlementTypekey:
                type: integer
                example: 59
              entitlementTypeDisplayname:
                type: string
                example: "AWSPolicy"
              accountname:
                type: string
                example: "245947"
              accountstatus:
                type: string
                example: "Manually Suspended"
              endpointname:
                type: string
                example: "AWS"
              entitlement_value:
                type: string
                example: "arn:aws:iam::661222050851:policy/CrossPolicy2"
              entstatus:
                type: integer
                example: 1
              securitysystemkey:
                type: integer
                example: 1
              securitysystemdisplayname:
                type: string
                example: "AWS"
              username:
                type: string
                example: "245947"
        errorCode:
          type: string
          example: "0"
        totalCount:
          type: integer
          example: 1
    UserListResponse:
      type: object
      properties:
        users:
          type: array
          items:
            type: object
            properties:
              username:
                type: string
                example: "admin"
        totalCount:
          type: integer
          example: 6
        errorCode:
          type: string
          example: "0" 
    GetChildEntitlementsResponse:
      type: object
      properties:
        displaycount:
          type: integer
          description: The number of displayed entitlements.
          example: 3
        msg:
          type: string
          description: The message indicating success or failure.
          example: "success"
        totalcount:
          type: integer
          description: The total number of child entitlements.
          example: 3
        childEntitlementsList:
          type: array
          items:
            type: object
            properties:
              customproperty4:
                type: string
                example: "/subscriptions/dd6c62d3-3fba-40d4-8eeb-678e48469c19"
              customproperty5:
                type: string
                example: "Enabled"
              customproperty1:
                type: string
                example: "Microsoft Azure Enterprise(Converted to EA)"
              endpointKey:
                type: integer
                example: 11
              description:
                type: string
                example: ""
              entitlement_glossary:
                type: string
                example: ""
              endpoint:
                type: string
                example: "Microsoft Azure Infrastructure"
              parententstatus:
                type: string
                example: "1"
              customproperty8:
                type: string
                example: "Off"
              entitlement_value:
                type: string
                example: "dd6c62d3-3fba-40d4-8eeb-678e48469c19"
              customproperty6:
                type: string
                example: "Public_2014-09-01"
              customproperty7:
                type: string
                example: "EnterpriseAgreement_2014-09-01"
              syscritical:
                type: string
                example: "0"
              entitlement_valuekey:
                type: string
                example: "176472"
              entitlementID:
                type: string
                example: "dd6c62d3-3fba-40d4-8eeb-678e48469c19"
              entitlementOwner:
                type: string
                example: ""
              entitlementTypeName:
                type: string
                example: "Subscription"
              entitlementType:
                type: string
                example: "Subscription"
              entitlementTypeKey:
                type: integer
                example: 83
              parententitlementvaluekey:
                type: integer
                example: 7
              requestForm:
                type: string
                example: "Request Form Table"
              displayname:
                type: string
                example: ""
              soxcritical:
                type: string
                example: "0"
              parententitlementvalue:
                type: string
                example: "CN=Saviynt_Azure_Admin,CN=Builtin,DC=corpAD,DC=saviynt,DC=com"
              status:
                type: string
                example: "1"
        errorcode:
          type: string
          description: Error code indicating success or failure.
          example: "0"          

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
